apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workforce-monitoring-grafana-public
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: workforce-monitoring-grafana
                port:
                  number: 80
